Hash pinning

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -13,6 +13,8 @@ jobs:
         runs-on: ubuntu-latest
         env:
             VERSION: 4.6.3
+            BINARY_SUM: a035258da32b77f966a5376f9fa29c30a6adde826a85ba918e1605bd1fc9823eba7d85f1dd5e748956bd2ba72827c0025ffa11bb82aec91128c407a2e723c99c
+            TEMPLATE_SUM: da606b61c10157844f8300172df374472665f95015495cb1a7cd132c40ede404faa96cc1016a4b9662db9909ddea69632c4948b2cd11163438dad4808881fb68
             SAVE_DIR: bin
         permissions:
           id-token: write
@@ -20,13 +22,13 @@ jobs:
           attestations: write
         steps:
             - name: Checkout repo
-              uses: actions/checkout@v6
+              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.0
               with:
                 persist-credentials: false
             
             - name: Cache Godot engine + export templates
               id: cache
-              uses: actions/cache@v5
+              uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9  # v6.0.0
               with:
                 path: ${{ env.SAVE_DIR }}/
                 key: godot-v${{ env.VERSION }}-linux64
@@ -35,7 +37,22 @@ jobs:
               if: steps.cache.outputs.cache-hit == ''
               run: |
                 curl -o ${{ env.SAVE_DIR }}/godot https://downloads.godotengine.org/?version=${{ env.VERSION }}&flavor=stable&slug=linux.x86_64.zip&platform=linux.64
+
+                if [ "$(sha512sum ${{ env.SAVE_DIR }}/godot)" = "${{ env.BINARY_SUM }}" ]; then
+                  echo "Godot binary checksum passed!"
+                else
+                  echo "Checksum for Godot binary did not pass! Action failed!"
+                  exit 1
+                fi
+
                 curl -o ${{ env.SAVE_DIR }}/export-templates.tpz https://downloads.godotengine.org/?version=${{ env.VERSION }}&flavor=stable&slug=export_templates.tpz&platform=templates
+
+                if [ "$(sha512sum ${{ env.SAVE_DIR }}/export-templates.tpz)" = "${{ env.TEMPLATE_SUM }}" ]; then
+                  echo "Godot export template checksum passed!"
+                else
+                  echo "Checksum for export templates did not pass! Action failed!"
+                  exit 1
+                fi
             
             - name: Make Godot executable & alias Godot
               run: |
@@ -51,15 +68,15 @@ jobs:
                     chmod +x ./build/neurojrpg
             
             - parallel:
-              - uses: actions/attest@v4
+              - uses: actions/attest@f7c74d28b9d84cb8768d0b8ca14a4bac6ef463e6  # v4.0.0
                 with:
                   subject-path: ./build/neurojrpg.exe
               
-              - uses: actions/attest@v4
+              - uses: actions/attest@f7c74d28b9d84cb8768d0b8ca14a4bac6ef463e6  # v4.0.0
                 with:
                   subject-path: ./build/neurojrpg.app
               
-              - uses: actions/attest@v4
+              - uses: actions/attest@f7c74d28b9d84cb8768d0b8ca14a4bac6ef463e6  # v4.0.0
                 with:
                   subject-path: ./build/neurojrpg
             
@@ -70,7 +87,7 @@ jobs:
             
             - name: Upload artifacts
               id: upload
-              uses: actions/upload-artifact@v7
+              uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.0
               with:
                 path: dist/*
                 name: neuro-sama_gef
@@ -85,16 +102,17 @@ jobs:
         steps:
             - name: Download artifacts
               id: download
-              uses: actions/download-artifact@v8
+              uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c  #v8.0.0
               with:
                 artifact-ids: ${{ needs.build.outputs.artifact-id }}
                 path: ./dist
             
             - name: Setup itch.io credentials
               env:
+                BUTLER_VERSION: 15.29.0
                 BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
               run: |
-                curl -o butler.zip https://broth.itch.zone/butler/linux-amd64/LATEST/archive/default
+                curl -o butler.zip https://broth.itch.zone/butler/linux-amd64/${{ env.BUTLER_VERSION }}/archive.zip
                 echo "Butler ZIP SHA-256: $(sha256sum butler.zip)"
                 unzip butler.zip
                 butler login
